### ISSUE TITLE
Add "init" command

### ISSUE THREAD

**Issue by greganswer** [greganswer/megit#3]
```ghekin
Feature: 
  As a developer
  I can run the init command
  So that I can fully initialize a Git repo using a template

  Scenario:
    Given
    When
    Then
```

## Tasks

**Should Have**
- [ ] Add issue and pull request templates

**Could Have**
- [ ] Ask the user what type of project they are creating (JS, Typescript, Ruby, etc.)
- [ ] Create `.gitignore` file based on project type
- [ ] Could be generated using [GitHub gitignore API](https://developer.github.com/v3/gitignore/)
